[package]
name = "workengine-adapters-worker"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true
description = "Workengine WorkerRunner adapters."

[dependencies]
workengine-application.workspace = true
workengine-domain.workspace = true
serde.workspace = true
serde_json.workspace = true
nix.workspace = true
tempfile.workspace = true

[dev-dependencies]

[lints]
workspace = true
